---
title: "Web Mapping & Analysis Tutorials"
description: |
  View the tutorials I created for web mapping and analysis in ArcGIS Online.
# author: []
date: 2021-03-28
categories: 
  - GIS
  - Course Materials
  - Neighborhoods
output:
  distill::distill_article:
    self_contained: false
preview: filter_day_of_week.gif
---

The Social Life of Neighborhoods was a course offered through Stanford's Sociology Department in the spring of 2021. The underlying goal of the course is to mount a quarter long
intellectual investigation of a neighborhood and the various processes that structure its “social life”— that is, the way it developed historically, reproduces itself on a daily basis, and is subjectively experienced by various individuals and groups. View the [course syllabus](https://drive.google.com/file/d/1Osjtn8YP1PE_DuZhy1rr3vSampJ_Pv3t/view?usp=sharing) to see a complete description of the course and all of the assignments.

I constructed tutorials on a weekly basis to prepare students for upcoming mapping assignments. The tutorials were published in a Gitbook that you can preview below and visit [here](https://bookdown.org/fis/social-life-of-neighborhoods). The repository for the code is linked below the preview. 


<iframe src="https://bookdown.org/fis/social-life-of-neighborhoods/" width="100%" height="500px" frameborder="0" allowfullscreen allow="geolocation"></iframe>

<a href="https://github.com/francine-stephens/social-life-of-neighborhoods" style="margin-left: 1em"> <button class="btn btn-outline-dark"> <i class="fab fa-github fa-lg"></i> Code</button> </a>
